### ISSUE TITLE
[Feature] 문서 열람 시간 Request API

### ISSUE THREAD

**Issue by yyj1453** [Globa-Seoil-Univ/globa-backend#36]
## 어떤 기능인가요?
* 사용자의 문서 열람 시간을 서버로 전송하는 api

## 작업 상세 내용
* 문서 내 시각화
    * 문서 별 날짜 별 열람 시간 누적 계산
* 전체 시각화
    * 날짜 별 열람 시간 누적 계산

## 참고할만한 자료 (선택)
> 추가하려는 기능에 대해서 참고할만한 스크린샷 또는 링크를 남겨주세요.

**Comment by seungyong** [comment]
### Request
1. 문서 ID
2. 공부 시간
