### ISSUE TITLE
[BUG] 알림 전체 요청 시 호스트 서버로부터 500 반환

### ISSUE THREAD

**Issue by yyj1453** [Globa-Seoil-Univ/globa-backend#52]
## 어떤 버그가 발생했나요?
* 알림 요청 시 호스트 서버로부터 Response Code로 500이 반환됨
* 메시지나 또 다른 정보 없이 500 코드만 반환됨

## 버그를 재현하기 위한 순서를 작성해주세요.
* method: GET
* path: "/notification"
* page: 1    /    count: 10    /    type: "a"

## 기대 결과
* 사용자 별 데이터베이스에 저장되어있는 알림 정보들을 정상적으로 호출

## 추가적인 설명
* 데이터베이스 컬럼 삭제 후 호스트 서버에서 처리가 안된 것으로 추정됨

**Comment by dbstjdqls14** [comment]
호스트 환경에서 Notification 컬럼의 is_read를 추가하였습니다. 확인 부탁드립니다. @yyj1453

**Comment by seungyong** [comment]
@dbstjdqls14 추가가 아니라 삭제입니다.
