### ISSUE TITLE
[BUG] 사용자 간 폴더 공유 에러

### ISSUE THREAD

**Issue by yyj1453** [Globa-Seoil-Univ/globa-backend#53]
## 어떤 버그가 발생했나요?
* 공유 초대를 받은 사용자가 초대 수락을 하지 않았는데도 공유가 됨

## 버그를 재현하기 위한 순서를 작성해주세요.
* method: POST
* path: "/folder/{folder_id}/share/user/{user_id}"
* body: "r/w"

## 기대 결과
* 공유 초대를 받은 사용자가 수락 버튼을 누르기 전까진 공유가 안됨
* 공유 초대를 받은 사용자가 수락 버튼을 누르면 공유가 완료되어 메인 페이지에 표시

## 추가적인 설명
* 없음

**Comment by dbstjdqls14** [comment]
recordService에서 invitationStatus 검사가 누락되어 있었습니다. 수정은 다 했고, 곧 머지 하겠습니다.
